# Generated by Django 2.2.1 on 2019-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='push_service_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='push_service_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
